### ISSUE TITLE
Unable to boot twrp-3.3.1-2-mermaid.img

### ISSUE THREAD

**Issue by MrDrMcCoy** [luk1337/android_device_sony_mermaid#1]
Hey @luk1337 , 

I am having trouble getting this to boot on my device. I have the I4213, and have tried various combinations of the following:

1. Start in green flashing mode and do `sudo fastboot reboot bootloader`, then `sudo fastboot boot twrp-3.3.1-2-mermaid.img`
2. Start in blue fastboot mode and do `sudo fastboot reboot bootloader`, then `sudo fastboot boot twrp-3.3.1-2-mermaid.img`
3. Start Android and do `sudo adb reboot bootloader`, then `sudo fastboot boot twrp-3.3.1-2-mermaid.img`

When I do this, it just hangs indefinitely after printing `Sending 'boot.img' (31552 KB)`.

I was initially running on Hak20's AOSP9 image, so I tried using newflasher to revert to stock with the image id of `I4213_Customized EU_1317-7514_53.0.A.14.47_R19A`, but I still had the same result as above. 

Is there something I'm missing? I would really appreciate any assistance you might be willing to give.

**Comment by luk1337** [comment]
Try using different USB port or maybe USB hub.

**Comment by MrDrMcCoy** [comment]
Thanks, @luk1337! I can't imagine why using a different machine helped, but it did. I am now running your LineageOS build, and it is working pretty well.

**Comment by luk1337** [comment]
That's cause Sony development team is bunch of incompetent idiots that can't even get usb implementation in bootloader right.
